/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import domen.Test;
import domen.TipTesta;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.ModelTabeleKorisnik;
import modeli.ModelTabeleTest;
import niti.OsvezavanjeKorisnickogPanelaNit;

/**
 *
 * @author Mina
 */
public class FrmKorisnik extends javax.swing.JFrame {
    
    private Korisnik prijavljen;
    private List<Test> listaTestova;

    /**
     * Creates new form FrmKorisnik
     */
    private FrmKorisnik() {
        initComponents();        
    }
    public FrmKorisnik(Korisnik prijavljen) {
        this();
        this.prijavljen = prijavljen;
        srediFormu();
        new OsvezavanjeKorisnickogPanelaNit(this).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVremePrijaveNaSistem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtVremePoslednjeSamoprocene = new javax.swing.JTextField();
        btnNovoTestiranje = new javax.swing.JButton();
        pnlUradjeniTestovi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTestovi = new javax.swing.JTable();
        txtStanje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Stanje:");

        jLabel2.setText("Vreme prijave:");

        jLabel3.setText("Vreme poslednje samoprocene:");

        btnNovoTestiranje.setText("Novo testiranje");
        btnNovoTestiranje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoTestiranjeActionPerformed(evt);
            }
        });

        pnlUradjeniTestovi.setBorder(javax.swing.BorderFactory.createTitledBorder("Uradjeni testovi"));

        tblTestovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTestovi);

        javax.swing.GroupLayout pnlUradjeniTestoviLayout = new javax.swing.GroupLayout(pnlUradjeniTestovi);
        pnlUradjeniTestovi.setLayout(pnlUradjeniTestoviLayout);
        pnlUradjeniTestoviLayout.setHorizontalGroup(
            pnlUradjeniTestoviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUradjeniTestoviLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlUradjeniTestoviLayout.setVerticalGroup(
            pnlUradjeniTestoviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUradjeniTestoviLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVremePoslednjeSamoprocene, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(txtVremePrijaveNaSistem)
                            .addComponent(txtStanje)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlUradjeniTestovi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNovoTestiranje, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVremePrijaveNaSistem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVremePoslednjeSamoprocene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovoTestiranje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlUradjeniTestovi, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoTestiranjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoTestiranjeActionPerformed
        this.setVisible(false);
        new FrmTest(this).setVisible(true);        
    }//GEN-LAST:event_btnNovoTestiranjeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKorisnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKorisnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKorisnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKorisnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKorisnik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoTestiranje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlUradjeniTestovi;
    private javax.swing.JTable tblTestovi;
    private javax.swing.JTextField txtStanje;
    private javax.swing.JTextField txtVremePoslednjeSamoprocene;
    private javax.swing.JTextField txtVremePrijaveNaSistem;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            this.setTitle("Korisnicki panel");
            Test zaPretragu = new Test(-1, null, null, false, null, prijavljen);
            listaTestova = Kontroler.getInstance().pretragaTestova(zaPretragu);
            tblTestovi.setModel(new ModelTabeleTest(listaTestova));
            
            txtVremePrijaveNaSistem.setEnabled(false);
            txtVremePrijaveNaSistem.setText(Kontroler.getInstance().formatDatum(prijavljen.getPoslednjaPrijava()));
            Test poslednjaSamoprocena = poslednjaSamoprocena();
            txtVremePoslednjeSamoprocene.setEnabled(false);
            if(poslednjaSamoprocena != null)
                txtVremePoslednjeSamoprocene.setText(Kontroler.getInstance().formatDatum(poslednjaSamoprocena.getDatum()));
            else
                txtVremePoslednjeSamoprocene.setText("Do sada niste radili test samoprocene");            
            txtStanje.setEnabled(false);
            txtStanje.setText(prijavljen.getStanje().toString());
            
            //tblTestovi.setColumnSelectionAllowed(false);
            //tblTestovi.setDragEnabled(false);            
            tblTestovi.setEnabled(false);
        } catch (Exception ex) {
            //Logger.getLogger(FrmKorisnik.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    public Test poslednjaSamoprocena() {
        if(listaTestova == null)
            return null;
        Test psp = null;
        for(Test t : listaTestova){
            if(t.getTip() != TipTesta.samoprocena)
                continue;
            if(psp == null || psp.getDatum().before(t.getDatum()))
                psp = t;
        }
        return psp;
    }

    public Korisnik getPrijavljen() {
        return prijavljen;
    }

    public void setPrijavljen(Korisnik prijavljen) {
        this.prijavljen = prijavljen;
    }

    public List<Test> getListaTestova() {
        return listaTestova;
    }

    public void setListaTestova(List<Test> listaTestova) {
        this.listaTestova = listaTestova;
    }

    public void osvezi() {
        try {
            prijavljen = Kontroler.getInstance().pretragaKorisnika(prijavljen).get(0);
            srediFormu();
        } catch (Exception ex) {
            //Logger.getLogger(FrmKorisnik.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}
