/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Odgovor;
import domen.Stanje;
import domen.StatusTesta;
import domen.Test;
import domen.TipTesta;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author Mina
 */
public class FrmTest extends javax.swing.JFrame {

    private FrmKorisnik frmKorisnik;
    private JComboBox[] cbs;

    /**
     * Creates new form FrmTest
     */
    private FrmTest() {
        initComponents();
    }

    public FrmTest(FrmKorisnik frmKorisnik) {
        this();
        this.frmKorisnik = frmKorisnik;
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPocniTestSamoprocene = new javax.swing.JButton();
        pnlTestSamoprocene = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbTemperatura = new javax.swing.JComboBox();
        cbKasalj = new javax.swing.JComboBox();
        cbMiris = new javax.swing.JComboBox();
        cbSlabost = new javax.swing.JComboBox();
        cbUkus = new javax.swing.JComboBox();
        btnPosaljiTestSamoprocene = new javax.swing.JButton();
        cbKontakt = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        pnlBrziIPCR = new javax.swing.JPanel();
        btnUradiBrziTest = new javax.swing.JButton();
        btnUradiPCR = new javax.swing.JButton();
        btnVratiSe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPocniTestSamoprocene.setText("Pocni test samoprocene");
        btnPocniTestSamoprocene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPocniTestSamoproceneActionPerformed(evt);
            }
        });

        pnlTestSamoprocene.setBorder(javax.swing.BorderFactory.createTitledBorder("Test samoprocene"));

        jLabel1.setText("Da li imate povisenu temperaturu?");

        jLabel2.setText("Da li kasljete?");

        jLabel3.setText("Da li osecate gubitak cula mirisa?");

        jLabel4.setText("Da li osecate opstu slabost?");

        jLabel5.setText("Da li osecate gubitak ili promenu cula ukusa?");

        cbTemperatura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbKasalj.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbMiris.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbSlabost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbUkus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPosaljiTestSamoprocene.setText("Posalji test");
        btnPosaljiTestSamoprocene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiTestSamoproceneActionPerformed(evt);
            }
        });

        cbKontakt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Da li ste bili u kontaktu sa zarazenom osobom?");

        javax.swing.GroupLayout pnlTestSamoproceneLayout = new javax.swing.GroupLayout(pnlTestSamoprocene);
        pnlTestSamoprocene.setLayout(pnlTestSamoproceneLayout);
        pnlTestSamoproceneLayout.setHorizontalGroup(
            pnlTestSamoproceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTestSamoproceneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTestSamoproceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTestSamoproceneLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTestSamoproceneLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbSlabost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTestSamoproceneLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbUkus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTestSamoproceneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbKasalj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTestSamoproceneLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTestSamoproceneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPosaljiTestSamoprocene))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTestSamoproceneLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(cbKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlTestSamoproceneLayout.setVerticalGroup(
            pnlTestSamoproceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTestSamoproceneLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(pnlTestSamoproceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pnlTestSamoproceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbTemperatura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTestSamoproceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKasalj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnlTestSamoproceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSlabost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlTestSamoproceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlTestSamoproceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbUkus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnPosaljiTestSamoprocene)
                .addContainerGap())
        );

        pnlBrziIPCR.setBorder(javax.swing.BorderFactory.createTitledBorder("Brzi test i PCR"));

        btnUradiBrziTest.setText("Uradi brzi test");
        btnUradiBrziTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUradiBrziTestActionPerformed(evt);
            }
        });

        btnUradiPCR.setText("Uradi PCR");
        btnUradiPCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUradiPCRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBrziIPCRLayout = new javax.swing.GroupLayout(pnlBrziIPCR);
        pnlBrziIPCR.setLayout(pnlBrziIPCRLayout);
        pnlBrziIPCRLayout.setHorizontalGroup(
            pnlBrziIPCRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBrziIPCRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUradiBrziTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUradiPCR)
                .addContainerGap())
        );
        pnlBrziIPCRLayout.setVerticalGroup(
            pnlBrziIPCRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBrziIPCRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBrziIPCRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUradiBrziTest)
                    .addComponent(btnUradiPCR))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnVratiSe.setText("Vrati se");
        btnVratiSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVratiSeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlBrziIPCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTestSamoprocene, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPocniTestSamoprocene, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVratiSe)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPocniTestSamoprocene)
                .addGap(18, 18, 18)
                .addComponent(pnlTestSamoprocene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBrziIPCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVratiSe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVratiSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVratiSeActionPerformed
        zatvoriFormu();
    }//GEN-LAST:event_btnVratiSeActionPerformed

    private void btnPocniTestSamoproceneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPocniTestSamoproceneActionPerformed
        pnlTestSamoprocene.setVisible(true);
    }//GEN-LAST:event_btnPocniTestSamoproceneActionPerformed

    private void btnPosaljiTestSamoproceneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiTestSamoproceneActionPerformed
        int brojDa = 0, brojNe = 0;
        for (JComboBox cb : cbs) {
            Odgovor odg = Odgovor.valueOf((String) cb.getSelectedItem());
            if (odg == Odgovor.izaberite) {
                JOptionPane.showMessageDialog(this, "Molimo vas da odgovorite na sva pitanja");
                return;
            }
            if (odg == Odgovor.da) {
                brojDa++;
            }
        }
        boolean pozitivan = brojDa >= 2;
        Test test = new Test(-1, TipTesta.samoprocena, new Date(), pozitivan, StatusTesta.poslato, frmKorisnik.getPrijavljen());
        try {
            test = Kontroler.getInstance().posaljiTest(test);
        } catch (Exception ex) {
            //Logger.getLogger(FrmTest.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }

        if (test.isPozitivan()) {
            JOptionPane.showMessageDialog(this, "Rezultat testa samoprocene je pozitivan. Potrebno je da uradite brzi test i/ili PCR test");
            pnlTestSamoprocene.setVisible(false);
            btnPocniTestSamoprocene.setVisible(false);
            pnlBrziIPCR.setVisible(true);
            btnVratiSe.setVisible(false);
            return;
        }
        if (frmKorisnik.getPrijavljen().getStanje() == Stanje.pod_nadzorom) {
            JOptionPane.showMessageDialog(this, "Rezultat testa samoprocene je negativan po drugi put, tako da nije potrebno da budete pod daljim nadzorom. ");
        } else {
            JOptionPane.showMessageDialog(this, "Rezultat testa samoprocene je negativan. U narednom periodu ćete biti pod nadzorom..");
        }
        zatvoriFormu();
        frmKorisnik.osvezi();
    }//GEN-LAST:event_btnPosaljiTestSamoproceneActionPerformed

    private void btnUradiBrziTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUradiBrziTestActionPerformed
        Test test = new Test(-1, TipTesta.brzi, new Date(), false, StatusTesta.poslato, frmKorisnik.getPrijavljen());
        try {
            test = Kontroler.getInstance().posaljiTest(test);
        } catch (Exception ex) {
            //Logger.getLogger(FrmTest.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }
        JOptionPane.showMessageDialog(this, "Rezultat brzog testa je " + (test.isPozitivan() ? "pozitivan. " : "negativan. "));
        btnVratiSe.setVisible(true);
        frmKorisnik.osvezi();
    }//GEN-LAST:event_btnUradiBrziTestActionPerformed

    private void btnUradiPCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUradiPCRActionPerformed
        Test test = new Test(-1, TipTesta.PCR, new Date(), false, StatusTesta.poslato, frmKorisnik.getPrijavljen());
        try {
            Kontroler.getInstance().posaljiTest(test);
        } catch (Exception ex) {
            //Logger.getLogger(FrmTest.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }
        JOptionPane.showMessageDialog(this, "PCR test je poslat. Status i rezultat možete da pratite na korisničkom panelu. ");
        btnVratiSe.setVisible(true);
        frmKorisnik.osvezi();
    }//GEN-LAST:event_btnUradiPCRActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPocniTestSamoprocene;
    private javax.swing.JButton btnPosaljiTestSamoprocene;
    private javax.swing.JButton btnUradiBrziTest;
    private javax.swing.JButton btnUradiPCR;
    private javax.swing.JButton btnVratiSe;
    private javax.swing.JComboBox cbKasalj;
    private javax.swing.JComboBox cbKontakt;
    private javax.swing.JComboBox cbMiris;
    private javax.swing.JComboBox cbSlabost;
    private javax.swing.JComboBox cbTemperatura;
    private javax.swing.JComboBox cbUkus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlBrziIPCR;
    private javax.swing.JPanel pnlTestSamoprocene;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        this.setTitle("Panel za testiranje");
        Test poslednjaSamoprocena = frmKorisnik.poslednjaSamoprocena();
        Date dps = poslednjaSamoprocena != null ? poslednjaSamoprocena.getDatum() : null;
        Date danas = new Date();
        boolean radjenDanas = dps != null && Kontroler.getInstance().formatDatum(danas).equals(Kontroler.getInstance().formatDatum(dps));        
        if (radjenDanas) {
            btnPocniTestSamoprocene.setVisible(false);
            pnlTestSamoprocene.setVisible(false);
            pnlBrziIPCR.setVisible(true);
        } else {
            pnlTestSamoprocene.setVisible(false);
            pnlBrziIPCR.setVisible(false);
        }

        inicijalizujNizCbs();

    }

    private void inicijalizujNizCbs() {
        cbs = new JComboBox[6];
        cbs[0] = cbKontakt;
        cbs[1] = cbTemperatura;
        cbs[2] = cbKasalj;
        cbs[3] = cbSlabost;
        cbs[4] = cbMiris;
        cbs[5] = cbUkus;

        for (JComboBox cb : cbs) {
            cb.removeAllItems();
            for (Odgovor odg : Odgovor.values()) {
                cb.addItem(odg.toString());
            }
            cb.setSelectedItem(Odgovor.izaberite.toString());
        }
    }

    private void zatvoriFormu() {
        this.setVisible(false);
        frmKorisnik.setVisible(true);
        this.dispose();
    }
}
